name: CICD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Run Checkstyle
      run: mvn checkstyle:check
    - name: Run SpotBugs
      run: mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs
    - name: Run JaCoCo Test Coverage
      run: mvn jacoco:report
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
       name: app-jar
       path: target/*.jar
    - name: Run OWASP Dependency Check
      run: mvn org.owasp:dependency-check-maven:check
